-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles Table (replaces 'users' and 'settings' tables)
-- Links to Supabase Auth.users
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  
  -- User data
  sites jsonb default '[]'::jsonb,
  tags jsonb default '[]'::jsonb,
  tag_order jsonb default '[]'::jsonb,
  site_order jsonb default '[]'::jsonb,
  settings jsonb default '{}'::jsonb,
  
  -- Membership system
  membership_tier integer default 1, -- 1=basic, 2=premium, 3=super
  stripe_customer_id text,
  subscription_status text default 'inactive', -- 'active', 'inactive', 'cancelled'
  subscription_end_date timestamp with time zone,
  
  -- Customization (tier 2+ only)
  theme_settings jsonb default '{}'::jsonb,
  font_settings jsonb default '{}'::jsonb,
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- 2. Wallpaper Categories Table
create table public.wallpaper_categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  name_en text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Categories (Public Read, Admin Write - assuming 'service_role' or manual insert for now)
alter table public.wallpaper_categories enable row level security;

create policy "Categories are viewable by everyone."
  on public.wallpaper_categories for select
  using ( true );

-- Initial Categories
insert into public.wallpaper_categories (name, name_en) values
('风景', 'Landscape'),
('纯色', 'Solid Color'),
('每日推荐', 'Daily Recommendation'),
('Custom', 'Custom')
on conflict do nothing;

-- 3. Wallpapers Table (replaces 'daily_wallpapers' and 'user_wallpapers')
create table public.wallpapers (
  id bigint generated by default as identity primary key,
  title text,
  url text not null,
  category text not null,
  source text default 'system', -- 'system' or 'user'
  user_id uuid references auth.users, -- null for system wallpapers
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Wallpapers
alter table public.wallpapers enable row level security;

create policy "Wallpapers are viewable by everyone."
  on public.wallpapers for select
  using ( true );

create policy "Users can upload their own wallpapers."
  on public.wallpapers for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own wallpapers."
  on public.wallpapers for delete
  using ( auth.uid() = user_id );

-- Function to handle new user signup (auto-create profile)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Drop existing trigger if it exists
drop trigger if exists on_auth_user_created on auth.users;

-- Trigger to call the function on sign up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
