-- ============================================
-- PREMIUM FEATURES MIGRATION
-- Add this after running the base migration
-- ============================================

-- 1. User Subscriptions Table
-- Track subscription history and Stripe payment details
create table public.user_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  stripe_subscription_id text unique,
  stripe_payment_intent_id text,
  tier integer not null, -- 2 or 3
  amount integer not null, -- in cents
  currency text default 'usd',
  status text not null, -- 'pending', 'completed', 'failed', 'refunded'
  started_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Subscriptions
alter table public.user_subscriptions enable row level security;

create policy "Users can view their own subscriptions."
  on public.user_subscriptions for select
  using ( auth.uid() = user_id );

-- Index for faster lookups
create index idx_user_subscriptions_user_id on public.user_subscriptions(user_id);
create index idx_user_subscriptions_stripe_id on public.user_subscriptions(stripe_subscription_id);

-- 2. Custom Themes Table (Optional - for future pre-defined theme library)
create table public.custom_themes (
  id bigint generated by default as identity primary key,
  name text not null,
  name_zh text, -- Chinese name
  description text,
  description_zh text, -- Chinese description
  css_variables jsonb not null, -- Store CSS custom properties
  is_premium boolean default false, -- Require tier 2+
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.custom_themes enable row level security;

create policy "Themes are viewable by everyone."
  on public.custom_themes for select
  using ( true );

-- Insert default themes
insert into public.custom_themes (name, name_zh, description, description_zh, css_variables, is_premium) values
('Handdrawn', '手绘风格', 'Default sketchy hand-drawn style', '默认手绘涂鸦风格', '{"--bg-color": "#f9f9f9", "--text-color": "#333333"}', false),
('Minimal', '极简风格', 'Clean and minimal design', '简洁极简设计', '{"--bg-color": "#ffffff", "--text-color": "#000000"}', true),
('Modern', '现代风格', 'Sleek modern interface', '时尚现代界面', '{"--bg-color": "#1a1a1a", "--text-color": "#ffffff"}', true),
('Glassmorphism', '毛玻璃风格', 'Frosted glass effect', '磨砂玻璃效果', '{"--bg-color": "rgba(255,255,255,0.1)", "--backdrop-filter": "blur(10px)"}', true)
on conflict do nothing;

-- 3. Upload Quota Tracking
create table public.upload_quota (
  user_id uuid references auth.users primary key,
  wallpaper_count integer default 0,
  max_wallpapers integer default 50,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.upload_quota enable row level security;

create policy "Users can view their own quota."
  on public.upload_quota for select
  using ( auth.uid() = user_id );

drop policy if exists "Users can update their own quota." on public.upload_quota;

-- Function to increment wallpaper count
create or replace function public.increment_wallpaper_count()
returns trigger as $$
begin
  insert into public.upload_quota (user_id, wallpaper_count)
  values (new.user_id, 1)
  on conflict (user_id) 
  do update set 
    wallpaper_count = upload_quota.wallpaper_count + 1,
    updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to auto-increment on wallpaper upload
create trigger on_wallpaper_upload
  after insert on public.wallpapers
  for each row 
  when (new.source = 'user')
  execute procedure public.increment_wallpaper_count();

-- Function to decrement wallpaper count
create or replace function public.decrement_wallpaper_count()
returns trigger as $$
begin
  update public.upload_quota
  set wallpaper_count = greatest(0, wallpaper_count - 1),
      updated_at = now()
  where user_id = old.user_id;
  return old;
end;
$$ language plpgsql security definer;

-- Trigger to auto-decrement on wallpaper delete
create trigger on_wallpaper_delete
  after delete on public.wallpapers
  for each row 
  when (old.source = 'user')
  execute procedure public.decrement_wallpaper_count();

-- 4. Helper Functions (needed by policies below)

-- Check if user can upload more wallpapers
create or replace function public.can_upload_wallpaper(p_user_id uuid)
returns boolean as $$
declare
  v_count integer;
  v_max integer;
begin
  select wallpaper_count, max_wallpapers 
  into v_count, v_max
  from public.upload_quota
  where user_id = p_user_id;
  
  if not found then
    return true; -- First upload
  end if;
  
  return v_count < v_max;
end;
$$ language plpgsql security definer;

-- 4. Enhanced RLS Policies for Tier-based Access

-- Policy: Only tier 2+ can upload to custom category
drop policy if exists "Users can upload their own wallpapers." on public.wallpapers;
drop policy if exists "Tier 2+ can upload custom wallpapers." on public.wallpapers;

create policy "Tier 2+ can upload custom wallpapers."
  on public.wallpapers for insert
  with check (
    auth.uid() = user_id 
    and (
      select membership_tier from public.profiles where id = auth.uid()
    ) >= 2
    and public.can_upload_wallpaper(auth.uid())
  );

-- 4.1 Protect profiles from client-side privilege escalation
create or replace function public.enforce_profile_update_restrictions()
returns trigger as $$
declare
  v_tier integer;
begin
  if auth.role() = 'service_role' then
    return new;
  end if;

  if auth.uid() is null or auth.uid() <> old.id then
    raise exception 'not allowed';
  end if;

  -- Block client-side membership escalation
  if new.membership_tier is distinct from old.membership_tier then
    raise exception 'membership_tier is managed by server';
  end if;

  select membership_tier into v_tier from public.profiles where id = auth.uid();
  v_tier := coalesce(v_tier, 1);

  -- Tier 1 cannot modify theme/font settings
  if v_tier < 2 then
    if new.theme_settings is distinct from old.theme_settings then
      raise exception 'theme_settings requires premium membership';
    end if;
    if new.font_settings is distinct from old.font_settings then
      raise exception 'font_settings requires premium membership';
    end if;
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_enforce_profile_update_restrictions on public.profiles;
create trigger trg_enforce_profile_update_restrictions
  before update on public.profiles
  for each row
  execute procedure public.enforce_profile_update_restrictions();

-- Update user membership tier (called by webhook)
create or replace function public.update_membership_tier(
  p_user_id uuid,
  p_tier integer,
  p_stripe_customer_id text,
  p_subscription_end_date timestamp with time zone
)
returns void as $$
begin
  update public.profiles
  set 
    membership_tier = p_tier,
    stripe_customer_id = p_stripe_customer_id,
    subscription_status = 'active',
    subscription_end_date = p_subscription_end_date,
    updated_at = now()
  where id = p_user_id;
end;
$$ language plpgsql security definer;

-- 6. Indexes for Performance
create index idx_profiles_membership_tier on public.profiles(membership_tier);
create index idx_profiles_stripe_customer on public.profiles(stripe_customer_id);
create index idx_wallpapers_user_category on public.wallpapers(user_id, category);
