-- Feedback Table for user submissions
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('bug', 'feature', 'other')),
  content text not null,
  email text,
  user_id uuid references auth.users,
  user_agent text,
  status text default 'new' check (status in ('new', 'reviewed', 'resolved', 'closed')),
  admin_notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Feedback
alter table public.feedback enable row level security;

-- Users can insert feedback
create policy "Anyone can submit feedback"
  on public.feedback for insert
  with check (true);

-- Users can only view their own feedback
create policy "Users can view their own feedback"
  on public.feedback for select
  using (auth.uid() = user_id);

-- Index for faster queries
create index if not exists feedback_user_id_idx on public.feedback(user_id);
create index if not exists feedback_status_idx on public.feedback(status);
create index if not exists feedback_created_at_idx on public.feedback(created_at desc);
